/****** Script Date: 02-01-2024 02:07:15 PM ******/

CREATE TABLE Student (
  StudentID INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
  FirstName VARCHAR(50) NOT NULL,
  LastName NVARCHAR(50) NOT NULL
);

CREATE TABLE Course (
  CourseID INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
  CourseName NVARCHAR(70) NOT NULL
);

CREATE TABLE Teacher (
  TeacherID INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
  FirstName NVARCHAR(50) NOT NULL,
  LastName NVARCHAR(50) NOT NULL
);

